odoo = [
 {"comment": "All oca repos",
  #"folder": "oca",
  "link": "git@github.com:OCA/",
  "repos": [
     "server-tools",
     "partner-contact",
     "product-variant",
     "product-attribute",
     "product-kitting",
     "management-system",
     "knowledge",
     "web",
     "website",
     "website-cms",
     "e-commerce",
     "survey",
     "social",
     "edi",
     "connector",
     "stock-logistics-reporting",
     "stock-logistics-warehouse",
     "stock-logistics-transport",
     "stock-logistics-tracking",
     "stock-logistics-workflow",
     "stock-logistics-barcode",
     "account-financial-tools",
     "account-payment",
     "account-invoicing",
     "account-invoice-reporting",
     "account-fiscal-rule",
     "account-consolidation",
     "account-financial-reporting",
     "account-closing",
     "account-budgeting",
     "account-analytic",
     "contract",
     "bank-statement-import",
     "bank-statement-reconcile",
     "bank-payment",
     "sale-workflow",
     "sale-reporting",
     "sale-financial",
     "margin-analysis",
     "commission",
     "crm",
     "pos",
     "delivery-carrier",
     "purchase-workflow",
     "purchase-reporting",
     "manufacture-reporting",
     "manufacture",
     "mis-builder",
     "rma",
     "project",
     "project-reporting",
     "program",
     "hr",
     "hr-timesheet",
     "department",
     "operating-unit",
     "donation",
     "queue",
     "community-data-files",
     "report-print-send",
     "reporting-engine",
     "multi-company",
     "event",
     "intrastat",
     "geospatial",
     "vertical-medical",
     "vertical-isp",
     "vertical-education",
     "vertical-community",
     "vertical-agriculture",
     "vertical-abbey",
     "vertical-association",
     "vertical-ngo",
     "vertical-travel",
     "vertical-hotel",
     "vertical-construction",
     "vertical-edition",
     "l10n-usa",
     "l10n-switzerland",
     "l10n-spain",
     "l10n-italy",
     "l10n-france",
     "l10n-belgium",
     "l10n-netherlands",
     "l10n-luxemburg",
     "l10n-argentina",
     "l10n-germany",
     "l10n-slovenia",
     "l10n-romania",
     "l10n-croatia",
     "server-ux",
     "currency"
     ]
 },
{"comment": "Cybro addons",
 #"folder": "cybro",
 "link": "git@github.com:CybroOdoo/",
 "repos": [
     "CybroAddons"
     ]
 },
{"comment": "Odoo PLM modules set: https://sourceforge.net/projects/openerpplm/",
 "link": "https://git.code.sf.net/p/openerpplm/",
 "repos": [
     "code"
    ]},
{"comment": "Interesting indeed!",
 "link": "git@github.com:it-projects-llc/",
 "repos": [
     "odoo-saas-tools",
     "misc-addons",
     "odoo-telegram",
     "access-addons",
     "website-addons",
     "pos-addons",
     "mail-addons",
     "partner",
     #"website",    fork from OCA
 ]
},
]
